services:
  db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: foobarhogepiyo
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: